import logging

from app.config import get_openai_api_key_value, get_settings
from app.utils.retry import run_with_retry

logger = logging.getLogger(__name__)
_UNAVAILABLE_MODELS: set[str] = set()


def _fallback_variants(query: str, n: int) -> list[str]:
    if n <= 1:
        return [query]
    candidates = [
        query,
        f"{query} implementation steps",
        f"{query} api reference",
        f"{query} troubleshooting",
        f"{query} prerequisites",
    ]
    deduped: list[str] = []
    seen: set[str] = set()
    for item in candidates:
        key = item.strip().lower()
        if key and key not in seen:
            seen.add(key)
            deduped.append(item.strip())
        if len(deduped) >= n:
            break
    while len(deduped) < n:
        deduped.append(query)
    return deduped


def _parse_variants(raw: str, original: str, n: int) -> list[str]:
    parsed: list[str] = [original]
    seen = {original.strip().lower()}
    for line in raw.splitlines():
        text = line.strip().lstrip("-").strip()
        if ". " in text[:4]:
            # Normalize "1. xxx" pattern.
            text = text.split(". ", 1)[1].strip()
        key = text.lower()
        if text and key not in seen:
            seen.add(key)
            parsed.append(text)
        if len(parsed) >= n:
            break
    while len(parsed) < n:
        parsed.append(original)
    return parsed[:n]


def generate_query_variants(query: str, n: int = 4) -> list[str]:
    """Generate multiple retrieval queries using LLM rewriting with fallback heuristics."""
    question = query.strip()
    if not question:
        return []

    if n <= 1:
        return [question]

    settings = get_settings()
    if not settings.openai_api_key:
        return _fallback_variants(question, n)

    try:
        from langchain_openai import ChatOpenAI

        model_candidates: list[str] = []
        for candidate in [settings.openai_chat_model, "gpt-4.1", "gpt-4o-mini"]:
            if candidate in _UNAVAILABLE_MODELS:
                continue
            if candidate not in model_candidates:
                model_candidates.append(candidate)

        prompt = (
            "Generate diverse search queries for technical documentation retrieval.\n"
            f"User question: {question}\n"
            f"Return {max(1, n - 1)} alternative queries as plain lines, no numbering."
        )
        for candidate_model in model_candidates:
            try:
                llm = ChatOpenAI(
                    model=candidate_model,
                    temperature=0,
                    api_key=get_openai_api_key_value(),
                )
                response = run_with_retry(
                    fn=lambda: llm.invoke(prompt),
                    max_attempts=settings.retry_max_attempts,
                    base_delay_seconds=settings.retry_base_seconds,
                    operation_name=f"query_rewrite_{candidate_model}",
                )
                content = (
                    response.content if isinstance(response.content, str) else str(response.content)
                )
                variants = _parse_variants(content, question, n)
                logger.info("query variants generated by %s: %s", candidate_model, variants)
                return variants
            except Exception as exc:
                text = str(exc).lower()
                if "model_not_found" in text or "does not exist" in text:
                    _UNAVAILABLE_MODELS.add(candidate_model)
                    continue
                raise
    except Exception:
        logger.warning("query rewrite failed, using fallback variants.")
        return _fallback_variants(question, n)
